version: '3'
services:
    gateway1:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5000
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        networks: 
                - my-net
        ports:
        - 5000:5000
    gateway2:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5001
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        networks: 
                - my-net
        ports:
        - 5001:5001
    gateway3:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5002
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        networks: 
                - my-net
        ports:
        - 5002:5002
    redis:
        image: redis:latest
        #network: my-net
        expose:
        - 6379
        ports:
        - 6379:6379
    bob:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway1:5000
                - ID=Bob
                - ADDRESS=http://bob:3000/
                - PORT=3000
        depends_on:
                - "gateway1"
                - "redis"
        networks: 
                - my-net
        ports:
        - 3000:3000
    alice:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway1:5000
                - ID=Alice
                - ADDRESS=http://alice:3001/
                - PORT=3001
        depends_on:
                - "gateway1"
                - "redis"
        networks: 
                - my-net
        ports:
        - 3001:3001
    bill:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway2:5001
                - ID=Bill
                - ADDRESS=http://bill:3002/
                - PORT=3002
        depends_on:
                - "gateway2"
                - "redis"
        networks: 
                - my-net
        ports:
        - 3002:3002
    james:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway2:5001
                - ID=James
                - ADDRESS=http://james:3003/
                - PORT=3003
        depends_on:
                - "gateway2"
                - "redis"
        networks: 
                - my-net
        ports:
        - 3003:3003
    william:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway3:5002
                - ID=William
                - ADDRESS=http://william:3004/
                - PORT=3004
        depends_on:
                - "gateway3"
                - "redis"
        networks: 
                - my-net
        ports:
        - 3004:3004
    eve:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway3:5002
                - ID=Eve
                - ADDRESS=http://eve:3005/
                - PORT=3005
        depends_on:
                - "gateway3"
                - "redis"
        networks: 
                - my-net
        ports:
        - 3005:3005
    pysyft:
        build: notebook-image
        networks: 
                - my-net
        ports: 
        - "8888:8888"
        - "6006:6006"
        volumes:
                - /Users/harshkasyap/Desktop/Experiments/SDDFLS:/workspace
networks:
        my-net:
